let handler = m => m

handler.before = function (m) {
    let user = global.db.data.users[m.sender]
    let role = (user.level <= 3) ? 'بارون V'
      : ((user.level >= 3) && (user.level <= 6)) ? 'بارون IV'
      : ((user.level >= 6) && (user.level <= 9)) ? 'بارون III'
      : ((user.level >= 9) && (user.level <= 12)) ? 'بارون II'
      : ((user.level >= 12) && (user.level <= 15)) ? 'بارون I'
      : ((user.level >= 15) && (user.level <= 18)) ? 'فيكونت V'
      : ((user.level >= 18) && (user.level <= 21)) ? 'فيكونت IV'
      : ((user.level >= 21) && (user.level <= 24)) ? 'فيكونت III'
      : ((user.level >= 24) && (user.level <= 27)) ? 'فيكونت II'
      : ((user.level >= 27) && (user.level <= 30)) ? 'فيكونت I'
      : ((user.level >= 30) && (user.level <= 33)) ? 'إيرل V'
      : ((user.level >= 33) && (user.level <= 36)) ? 'إيرل IV'
      : ((user.level >= 36) && (user.level <= 39)) ? 'إيرل III'
      : ((user.level >= 39) && (user.level <= 42)) ? 'إيرل II'
      : ((user.level >= 42) && (user.level <= 45)) ? 'إيرل I'
      : ((user.level >= 45) && (user.level <= 48)) ? 'ماركيز V'
      : ((user.level >= 48) && (user.level <= 51)) ? 'ماركيز IV'
      : ((user.level >= 51) && (user.level <= 54)) ? 'ماركيز III'
      : ((user.level >= 54) && (user.level <= 57)) ? 'ماركيز II'
      : ((user.level >= 57) && (user.level <= 60)) ? 'ماركيز I'
      : ((user.level >= 60) && (user.level <= 63)) ? 'دوق V'
      : ((user.level >= 63) && (user.level <= 66)) ? 'دوق IV'
      : ((user.level >= 66) && (user.level <= 69)) ? 'دوق III'
      : ((user.level >= 69) && (user.level <= 71)) ? 'دوق II'
      : ((user.level >= 71) && (user.level <= 74)) ? 'دوق I'
      : ((user.level >= 74) && (user.level <= 77)) ? 'جنرال V'
      : ((user.level >= 77) && (user.level <= 80)) ? 'جنرال IV'
      : ((user.level >= 80) && (user.level <= 83)) ? 'جنرال III'
      : ((user.level >= 83) && (user.level <= 86)) ? 'جنرال II'
      : ((user.level >= 86) && (user.level <= 89)) ? 'جنرال I'
      : ((user.level >= 89) && (user.level <= 91)) ? 'جنرال اسطوري V'
      : ((user.level >= 91) && (user.level <= 94)) ? 'جنرال اسطوري IV'
      : ((user.level >= 94) && (user.level <= 97)) ? 'جنرال اسطوري III'
      : ((user.level >= 97) && (user.level <= 100)) ? 'جنرال اسطوري II'
      : ((user.level >= 100) && (user.level <= 105)) ? 'جنرال اسطوري I'      
      : ((user.level >= 105) && (user.level <= 120)) ? 'ادميرال'
      : ((user.level >= 120) && (user.level <= 150)) ? 'ادميرال V'
      : ((user.level >= 150) && (user.level <= 160)) ? 'ادميرال VI'
      : ((user.level >= 160) && (user.level <= 170)) ? 'ادميرال III'
      : ((user.level >= 170) && (user.level <= 185)) ? 'ادميرال II'
      : ((user.level >= 185) && (user.level <= 200)) ? 'ادميرال I'
      : ((user.level >= 200) && (user.level <= 400)) ? 'يونكو III'
      : ((user.level >= 405) && (user.level <= 700)) ? 'يونكو II'
      : ((user.level >= 700) && (user.level <= 1000)) ? 'يونكو I'
      : '👑مـلـك الـقـراصـنـة👑'

    user.role = role
    return true
}

export default handler
